#data Cleaning

In [70]:
#read the data
import pandas as pd

df = pd.read_csv('Accidental_Drug_Related_Deaths.csv')

In [71]:
#the first 5 row
df.head(5)

,Date,Date Type,Age,Sex,Race,Ethnicity,Residence City,Residence County,Residence State,Injury City,...,Xylazine,Gabapentin,Opiate NOS,Heroin/Morph/Codeine,Other Opioid,Any Opioid,Other,ResidenceCityGeo,InjuryCityGeo,DeathCityGeo
0,05/29/2012,Date of death,37.0,Male,Black,NaN,STAMFORD,FAIRFIELD,NaN,STAMFORD,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"STAMFORD, CT\n(41.051924, -73.539475)","STAMFORD, CT\n(41.051924, -73.539475)","CT\n(41.575155, -72.738288)"
1,06/27/2012,Date of death,37.0,Male,White,NaN,NORWICH,NEW LONDON,NaN,NORWICH,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"NORWICH, CT\n(41.524304, -72.075821)","NORWICH, CT\n(41.524304, -72.075821)","Norwich, CT\n(41.524304, -72.075821)"
2,03/24/2014,Date of death,28.0,Male,White,NaN,HEBRON,NaN,NaN,HEBRON,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"HEBRON, CT\n(41.658069, -72.366324)","HEBRON, CT\n(41.658069, -72.366324)","Marlborough, CT\n(41.632043, -72.461309)"
3,12/31/2014,Date of death,26.0,Female,White,NaN,BALTIC,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"BALTIC, CT\n(41.617221, -72.085031)","CT\n(41.575155, -72.738288)","Baltic, CT\n(41.617221, -72.085031)"
4,01/16/2016,Date of death,41.0,Male,White,NaN,SHELTON,FAIRFIELD,CT,SHELTON,...,NaN,NaN,NaN,NaN,NaN,Y,NaN,"SHELTON, CT\n(41.316843, -73.092968)","SHELTON, CT\n(41.316843, -73.092968)","Bridgeport, CT\n(41.179195, -73.189476)"

In [72]:
# List of columns to be deleted
columns_to_remove = [
    'Date Type', 'Ethnicity', 'Residence County', 'Residence State', 
    'Injury City', 'Injury County', 'Injury State', 'Injury Place', 
    'Description of Injury', 'Death County', 'Death State', 'Location', 
    'Location if Other', 'Cause of Death', 'Manner of Death', 
    'Other Significant Conditions ', 'Heroin death certificate (DC)', 
    'Fentanyl Analogue', 'Oxycodone', 'Oxymorphone', 'Hydrocodone', 
    'Meth/Amphetamine', 'Amphet', 'Tramad', 'Hydromorphone', 
    'Morphine (Not Heroin)', 'Xylazine', 'Gabapentin', 'Opiate NOS', 
    'Heroin/Morph/Codeine', 'Other Opioid', 'Other', 
    'ResidenceCityGeo', 'InjuryCityGeo', 'DeathCityGeo'
]

df = df.drop(columns=columns_to_remove)

In [73]:
df.head(5)

,Date,Age,Sex,Race,Residence City,Death City,Heroin,Cocaine,Fentanyl,Ethanol,Benzodiazepine,Methadone,Any Opioid
0,05/29/2012,37.0,Male,Black,STAMFORD,NaN,NaN,Y,NaN,NaN,NaN,NaN,NaN
1,06/27/2012,37.0,Male,White,NORWICH,NORWICH,Y,NaN,NaN,NaN,NaN,NaN,NaN
2,03/24/2014,28.0,Male,White,HEBRON,MARLBOROUGH,Y,NaN,NaN,NaN,NaN,NaN,NaN
3,12/31/2014,26.0,Female,White,BALTIC,BALTIC,Y,NaN,NaN,NaN,NaN,NaN,NaN
4,01/16/2016,41.0,Male,White,SHELTON,BRIDGEPORT,NaN,NaN,Y,NaN,NaN,NaN,Y

In [74]:
df.isna().sum()

Date                 0
Age                  2
Sex                  8
Race                24
Residence City     389
Death City           5
Heroin            5855
Cocaine           6031
Fentanyl          3530
Ethanol           6732
Benzodiazepine    6964
Methadone         8388
Any Opioid        2921
dtype: int64

In [75]:
df["Age"] = df["Age"].fillna(df["Age"].mean())

In [76]:
df['Date'] = pd.to_datetime(df['Date'])
df['Date'] = df['Date'].astype(int) // 10**9  # يحول إلى ثواني منذ 1970-01-01

In [77]:
df.fillna("N", inplace=True)

,Date,Age,Sex,Race,Residence City,Death City,Heroin,Cocaine,Fentanyl,Ethanol,Benzodiazepine,Methadone,Any Opioid
0,1338249,37.0,Male,Black,STAMFORD,N,N,Y,N,N,N,N,N
1,1340755,37.0,Male,White,NORWICH,NORWICH,Y,N,N,N,N,N,N
2,1395619,28.0,Male,White,HEBRON,MARLBOROUGH,Y,N,N,N,N,N,N
3,1419984,26.0,Female,White,BALTIC,BALTIC,Y,N,N,N,N,N,N
4,1452902,41.0,Male,White,SHELTON,BRIDGEPORT,N,N,Y,N,N,N,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9197,1634601,56.0,Male,Black or African American,STAMFORD,STAMFORD,N,Y,N,N,N,N,Y
9198,1620086,48.0,Male,Black or African American,WEST HAVEN,NEW HAVEN,N,Y,N,Y,N,N,N
9199,1621036,59.0,Male,White,WETHERSFIELD,HARTFORD,N,Y,N,N,N,N,N
9200,1622160,68.0,Male,Black or African American,HARTFORD,HARTFORD,N,Y,N,N,N,N,N
9201,1640304,29.0,Male,White,SEYMOUR,SEYMOUR,N,N,Y,N,N,Y,Y

In [78]:
Any_yes_no = {
    "Y": 1,
    "N": 0,
    "Y POPS":1,
    "Y (PTCH)":1,
    "P":1
}

cols = ['Heroin','Cocaine','Fentanyl',"Ethanol",'Benzodiazepine','Methadone','Any Opioid']

df[cols] = df[cols].replace(Any_yes_no)

In [79]:
Race = {
    'Black':0,
    'White':1
}
df['Race'] = df['Race'].map(Race)

In [80]:
sex = {
    'Female':0,
    "Male": 1
}
df['Sex']=df['Sex'].map(sex)

In [81]:
# LabelEncoder to convert Gender Department
from sklearn.preprocessing import LabelEncoder

categorical_cols = df.select_dtypes(include='str').columns
le=LabelEncoder()
for col in categorical_cols:
    df[col]= le.fit_transform(df[col].astype(str))

In [82]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9202 entries, 0 to 9201
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Date            9202 non-null   int64
 1   Age             9202 non-null   float64
 2   Sex             9194 non-null   float64
 3   Race            8760 non-null   float64
 4   Residence City  9202 non-null   int64
 5   Death City      9202 non-null   int64
 6   Heroin          9202 non-null   object
 7   Cocaine         9202 non-null   object
 8   Fentanyl        9202 non-null   object
 9   Ethanol         9202 non-null   object
 10  Benzodiazepine  9202 non-null   object
 11  Methadone       9202 non-null   object
 12  Any Opioid      9202 non-null   object
dtypes: float64(3), int64(3), object(7)
memory usage: 934.7+ KB

In [83]:
df['Race'] =df['Race'].fillna(df['Race'].mean())
df['Sex'] =df['Sex'].fillna(df['Sex'].mean())

In [84]:
df.isna().sum()

Date              0
Age               0
Sex               0
Race              0
Residence City    0
Death City        0
Heroin            0
Cocaine           0
Fentanyl          0
Ethanol           0
Benzodiazepine    0
Methadone         0
Any Opioid        0
dtype: int64

In [85]:
df = df.astype(int)

In [86]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9202 entries, 0 to 9201
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Date            9202 non-null   int64
 1   Age             9202 non-null   int64
 2   Sex             9202 non-null   int64
 3   Race            9202 non-null   int64
 4   Residence City  9202 non-null   int64
 5   Death City      9202 non-null   int64
 6   Heroin          9202 non-null   int64
 7   Cocaine         9202 non-null   int64
 8   Fentanyl        9202 non-null   int64
 9   Ethanol         9202 non-null   int64
 10  Benzodiazepine  9202 non-null   int64
 11  Methadone       9202 non-null   int64
 12  Any Opioid      9202 non-null   int64
dtypes: int64(13)
memory usage: 934.7 KB

In [87]:
df.sample(10)

,Date,Age,Sex,Race,Residence City,Death City,Heroin,Cocaine,Fentanyl,Ethanol,Benzodiazepine,Methadone,Any Opioid
1772,1636502,62,0,0,310,151,0,0,1,0,0,0,1
791,1614384,39,1,1,107,18,0,0,1,0,1,0,1
4237,1583193,51,0,1,107,54,0,0,1,0,1,0,1
2474,1409270,24,0,1,7,3,1,0,0,0,0,0,0
4413,1417478,50,0,1,42,21,0,0,0,0,1,0,0
1911,1386028,44,0,1,158,79,0,1,0,0,0,0,0
2476,1575417,18,1,0,336,166,0,0,1,0,0,0,1
6125,1327276,31,0,1,79,79,0,0,0,0,0,0,0
2923,1370995,49,1,1,15,138,1,1,0,0,0,0,0
7035,1588636,58,1,0,278,137,1,0,1,0,1,0,1

split

In [88]:
from sklearn.model_selection import train_test_split

X= df.drop(columns="Fentanyl")
y = df["Fentanyl"]

X_train ,X_test,y_train,y_test = train_test_split(
    X , y , test_size=0.2 , random_state=42
)

preprocessing

In [89]:
from sklearn.preprocessing import StandardScaler

scaler =StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

SMOTE

In [90]:
from imblearn.over_sampling import SMOTE

smote = SMOTE(random_state=42)
X_train_bal, y_train_bal = smote.fit_resample(X_train_scaled, y_train)

decomposition

In [91]:
from sklearn.decomposition import PCA
pca =PCA(n_components=3)

X_train_pca =pca.fit_transform(X_train_bal)
X_test_pca = pca.transform(X_test_scaled)

Modeling

In [92]:

from sklearn.linear_model import LogisticRegression

LR_model =LogisticRegression(
    max_iter=1000,
    class_weight='balanced'
)

LR_model.fit(X_train_pca,y_train_bal)

LogisticRegression(class_weight='balanced', max_iter=1000)

In [93]:
#LogisticRegression model report
from sklearn.metrics import classification_report ,accuracy_score,confusion_matrix

LR_model_pred =LR_model.predict(X_test_pca)
print("Accuracy : ", accuracy_score(y_test,LR_model_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test,LR_model_pred))
print("\nClassification Report:\n", classification_report(y_test,LR_model_pred))

Accuracy :  0.7365562194459533

Confusion Matrix:
 [[516 201]
 [284 840]]

Classification Report:
               precision    recall  f1-score   support

           0       0.65      0.72      0.68       717
           1       0.81      0.75      0.78      1124

    accuracy                           0.74      1841
   macro avg       0.73      0.73      0.73      1841
weighted avg       0.74      0.74      0.74      1841

In [94]:
# GridSearch for RandomForestClassifier model (take a time)
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestClassifier
param_grid = {
    "n_estimators":[100,200,350],
    'max_depth':[5,10,15],
}
grid = GridSearchCV(RandomForestClassifier(), param_grid, cv=5, n_jobs=-1, verbose=2, scoring='accuracy')
grid.fit(X_train_pca,y_train_bal)
print("The best settings for the model are:", grid.best_params_)

Fitting 5 folds for each of 9 candidates, totalling 45 fits
The best settings for the model are: {'max_depth': 15, 'n_estimators': 100}

In [95]:
#RandomForestClassifier model
from sklearn.ensemble import RandomForestClassifier

RF_model =RandomForestClassifier(
    n_estimators=350,
    max_depth=5,
    class_weight="balanced"
)
RF_model.fit(X_train_pca,y_train_bal)

RandomForestClassifier(class_weight='balanced', max_depth=5, n_estimators=350)

In [96]:
#RandomForestClassifier model report
from sklearn.metrics import classification_report ,accuracy_score,confusion_matrix

RF_model_y_pred =RF_model.predict(X_test_pca)
print("Accuracy : ", accuracy_score(y_test,RF_model_y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test,RF_model_y_pred))
print("\nClassification Report:\n", classification_report(y_test,RF_model_y_pred))

Accuracy :  0.7175448126018468

Confusion Matrix:
 [[600 117]
 [403 721]]

Classification Report:
               precision    recall  f1-score   support

           0       0.60      0.84      0.70       717
           1       0.86      0.64      0.73      1124

    accuracy                           0.72      1841
   macro avg       0.73      0.74      0.72      1841
weighted avg       0.76      0.72      0.72      1841

In [97]:
# GridSearch for XGB Classifier model (take a time)
from sklearn.model_selection import GridSearchCV
from xgboost  import XGBClassifier
param_grid = {
    "n_estimators":[100,200,350],
    'max_depth':[15,20,50],
    "learning_rate":[0.1]
    
}
grid = GridSearchCV(XGBClassifier(), param_grid, cv=3, n_jobs=-1, verbose=2, scoring='recall')
grid.fit(X_train_pca,y_train_bal)
print("The best settings for the model are:", grid.best_params_)

Fitting 3 folds for each of 9 candidates, totalling 27 fits
The best settings for the model are: {'learning_rate': 0.1, 'max_depth': 50, 'n_estimators': 350}

In [98]:
# XGBClassifier model
from xgboost  import XGBClassifier
XGB_model = XGBClassifier(
    scale_pos_weight=9, 
    learning_rate=0.1,
    max_depth=15, 
    n_estimators=100
)
XGB_model.fit(X_train_pca,y_train_bal)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=0.1, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=15,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=100,
              n_jobs=None, num_parallel_tree=None, ...)

In [99]:
from sklearn.metrics import classification_report ,accuracy_score,confusion_matrix

XGB_model_y_pred =XGB_model.predict(X_test_pca)
print("Accuracy : ", accuracy_score(y_test,XGB_model_y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test,XGB_model_y_pred))
print("\nClassification Report:\n", classification_report(y_test,XGB_model_y_pred))

Accuracy :  0.7360130363932645

Confusion Matrix:
 [[363 354]
 [132 992]]

Classification Report:
               precision    recall  f1-score   support

           0       0.73      0.51      0.60       717
           1       0.74      0.88      0.80      1124

    accuracy                           0.74      1841
   macro avg       0.74      0.69      0.70      1841
weighted avg       0.74      0.74      0.72      1841